# Упражнения на работу с pandas

## Упражнение № 1

In [5]:
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [6]:
import pandas as pd

series1 = pd.Series(mylist)
series2 = pd.Series(myarr)
series3 = pd.Series(mydict)

print(f"series1:\n{series1}\n")
print(f"series2:\n{series2}\n")
print(f"series3:\n{series3}\n")

series1:
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

series2:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

series3:
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32



## Упражнение № 2

In [7]:
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [8]:
df = ser.to_frame().reset_index()
print(f"Преобразованный ряд в датафрейм с новым столбцом:\n{df}")

Преобразованный ряд в датафрейм с новым столбцом:
   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25


## Упражнение № 3

In [9]:
import numpy as np

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [10]:
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)

df = pd.concat([ser1, ser2], axis=1)
df = pd.DataFrame({ "ser1": ser1, "ser2": ser2 })
print(f"Объединённый датафрейм из двух рядов:\n{df}")

Объединённый датафрейм из двух рядов:
   ser1  ser2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25


## Упражнение № 4

In [11]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
ser = pd.Series(mylist)

In [12]:
ser.name = "latin_letters"
print(f"С добавлением названия столбца:\n{ser}")

С добавлением названия столбца:
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, dtype: object


## Упражнение № 5

In [13]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1 = ser1[~ser1.isin(ser2)]
print(f"Очищенный первый ряд от значений второго ряда:\n{ser1}")

Очищенный первый ряд от значений второго ряда:
0    1
1    2
2    3
dtype: int64


## Упражнение № 6

In [14]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [15]:
series_union = pd.Series(np.union1d(ser1, ser2))
series_intersection = pd.Series(np.intersect1d(ser1, ser2))

ser = series_union[~series_union.isin(series_intersection)]
print(f"Не являются общими для двух рядов:\n{ser}")

Не являются общими для двух рядов:
0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


## Упражнение № 7

In [16]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [17]:
print(f"Исходные данные:\n{ser}\n")
names = [
    "Минимальное значение",
    "25-й процентиль",
    "Медиана",
    "75-й процентиль",
    "Максимальное значение",
]
results = np.percentile(ser, q=[0, 25, 50, 75, 100])
pretty_results = np.stack((names, results), axis=1)
print(pretty_results)

Исходные данные:
0     13.467333
1      9.742224
2      9.588933
3      9.495910
4      4.027130
5      0.397930
6      7.445117
7     16.906232
8      1.673452
9      5.246440
10     4.799117
11    14.841613
12    14.030644
13    11.547657
14     8.626953
15    16.676896
16    16.247564
17    17.808913
18    14.822488
19    13.219919
20     5.738528
21    10.922188
22     7.206419
23    14.952368
24    14.489190
dtype: float64

[['Минимальное значение' '0.3979299863593653']
 ['25-й процентиль' '7.206418925643257']
 ['Медиана' '10.922188102257866']
 ['75-й процентиль' '14.822488332629923']
 ['Максимальное значение' '17.808912656784344']]


## Упражнение № 8

In [18]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [19]:
print(f"Исходные данные:\n{ser}\n")
uniques = ser.value_counts()
print(f"Частота встречаемости каждого уникального значения:\n{uniques}\n")

Исходные данные:
0     b
1     f
2     a
3     h
4     h
5     a
6     c
7     a
8     d
9     g
10    f
11    f
12    h
13    d
14    e
15    g
16    e
17    g
18    b
19    d
20    d
21    h
22    b
23    c
24    f
25    g
26    d
27    g
28    d
29    g
dtype: object

Частота встречаемости каждого уникального значения:
d    6
g    6
f    4
h    4
b    3
a    3
c    2
e    2
Name: count, dtype: int64



## Упражнение № 9

In [20]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [21]:
print(f"Исходные данные:\n{ser}\n")
uniques = ser.value_counts()
print(f"Частота встречаемости каждого уникального значения:\n{uniques}\n")

top_2_uniques = uniques[:2]
print(f"Топ 2:\n{top_2_uniques}\n")


ser[~ser.isin(uniques.index[:2])] = 'Прочее'
print(f"Два наиболее встречающихся оставлены, другие заменены на 'Прочее':\n{ser}")

Исходные данные:
0     2
1     4
2     2
3     1
4     3
5     4
6     2
7     3
8     2
9     1
10    1
11    2
dtype: int32

Частота встречаемости каждого уникального значения:
2    5
1    3
4    2
3    2
Name: count, dtype: int64

Топ 2:
2    5
1    3
Name: count, dtype: int64

Два наиболее встречающихся оставлены, другие заменены на 'Прочее':
0          2
1     Прочее
2          2
3          1
4     Прочее
5     Прочее
6          2
7     Прочее
8          2
9          1
10         1
11         2
dtype: object


D:\Temp\ipykernel_34608\1830326190.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Прочее' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(uniques.index[:2])] = 'Прочее'


## Упражнение № 10

In [22]:
ser = pd.Series(np.random.random(20))

In [23]:
print(f"Исходные данные:\n{ser}\n")

cut_ser = pd.qcut(
                ser, 
                q=[0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1], 
                labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']
)
print(f"Значения заменены на децентили:\n{cut_ser}\n")

Исходные данные:
0     0.617501
1     0.846650
2     0.358753
3     0.671321
4     0.342458
5     0.152114
6     0.464795
7     0.048730
8     0.085206
9     0.336209
10    0.045159
11    0.455316
12    0.333636
13    0.813407
14    0.782109
15    0.001237
16    0.925824
17    0.101642
18    0.804162
19    0.892897
dtype: float64

Значения заменены на децентили:
0      7th
1      9th
2      5th
3      7th
4      5th
5      3rd
6      6th
7      2nd
8      2nd
9      4th
10     1st
11     6th
12     4th
13     9th
14     8th
15     1st
16    10th
17     3rd
18     8th
19    10th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']



## Упражнение № 11

In [24]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [25]:
print(f"Исходные данные:\n{ser}\n")

df = pd.DataFrame(ser.values.reshape(7, 5))
print(f"Датафрейм с 7 строками и 5 столбцами:\n{df}\n")

Исходные данные:
0     9
1     6
2     2
3     9
4     3
5     1
6     3
7     6
8     3
9     8
10    1
11    5
12    1
13    8
14    2
15    8
16    8
17    3
18    4
19    2
20    1
21    2
22    7
23    6
24    7
25    8
26    5
27    4
28    4
29    6
30    2
31    9
32    3
33    6
34    8
dtype: int32

Датафрейм с 7 строками и 5 столбцами:
   0  1  2  3  4
0  9  6  2  9  3
1  1  3  6  3  8
2  1  5  1  8  2
3  8  8  3  4  2
4  1  2  7  6  7
5  8  5  4  4  6
6  2  9  3  6  8



## Упражнение № 12

In [26]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [27]:
print(f"Исходные данные:\n{ser}\n")

indexes = np.argwhere(ser % 3 == 0)
print(f"Позиции чисел, кратных 3, из исходного ряда:\n{indexes}\n")

Исходные данные:
0    4
1    6
2    4
3    2
4    6
5    9
6    3
dtype: int32

Позиции чисел, кратных 3, из исходного ряда:
[[1]
 [4]
 [5]
 [6]]



## Упражнение № 13

In [28]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [29]:
# print(f"Исходные данные:\n{ser}\n")

poses = ser.take(pos)
print(f"Элементы, находящиеся на позициях в списке:\n{poses}\n")

Элементы, находящиеся на позициях в списке:
0     a
4     e
8     i
14    o
20    u
dtype: object



## Упражнение № 14

In [30]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [31]:
df = pd.concat([ser1, ser2], axis=1)
print(f"Объедининённые по вертикали и горизонтали ряды:\n{df}")

Объедининённые по вертикали и горизонтали ряды:
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


## Упражнение № 15

In [32]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [33]:
print("Позиции элементов `ser2` в `ser1` в виде списка")
[pd.Index(ser1).get_loc(i) for i in ser2]

Позиции элементов `ser2` в `ser1` в виде списка


[5, 4, 0, 8]

## Упражнение № 16

In [34]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [35]:
print(truth)
print(pred)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.293018
1    1.635737
2    2.115362
3    3.219789
4    4.233889
5    5.450798
6    6.611191
7    7.184811
8    8.782917
9    9.873949
dtype: float64


In [36]:
print(f"Среднеквадратическая ошибка рядов:\n{np.mean((truth - pred) ** 2)}")

Среднеквадратическая ошибка рядов:
0.2594014165142816


## Упражнение № 17

In [37]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [38]:
print(f"Каждое слово с заглавной буквы:\n{ser.map(lambda word: word.capitalize())}")

Каждое слово с заглавной буквы:
0     How
1      To
2    Kick
3    Ass?
dtype: object


## Упражнение № 18

In [39]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [40]:
print(f"Число символов в кажом слове:\n{ser.map(lambda word: len(word))}")

Число символов в кажом слове:
0    3
1    2
2    4
3    4
dtype: int64


## Упражнение № 19

In [41]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [42]:
print(f"Разность между последовательно идущими числами:\n{ser.diff().tolist()}\n")
print(f"Разность разностей между последовательно идущими числами:\n{ser.diff().diff().tolist()}")

Разность между последовательно идущими числами:
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

Разность разностей между последовательно идущими числами:
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


## Упражнение № 20

In [43]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [44]:
ser.map(lambda date: pd.to_datetime(date))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

## Упражнение № 21

In [45]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [46]:
dates = ser.map(lambda date: pd.to_datetime(date))

print("Date:\t\t\t", dates.dt.day.tolist())
print("Week number:\t\t", dates.dt.isocalendar().week.tolist())
print("Day number of year:\t", dates.dt.dayofyear.tolist())
print("Day of week:\t\t", dates.dt.day_name().tolist())

Date:			 [1, 2, 3, 4, 5, 6]
Week number:		 [53, 5, 9, 14, 19, 23]
Day number of year:	 [1, 33, 63, 94, 125, 157]
Day of week:		 ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


## Упражнение № 22

In [47]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [48]:
dates = ser.map(lambda date: pd.to_datetime(date).replace(day = 4))
print(f"Замена на даты, начинающиеся с 4-го числа соответствующего месяца:\n{dates}")

Замена на даты, начинающиеся с 4-го числа соответствующего месяца:
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


## Упражнение № 23

In [49]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [50]:
from collections import Counter

vowels = "eyuioa"
vowels_count = 2

word_checks = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list(vowels)]) >= vowels_count)

print(f"Слова, содержащие не менее 2 гласных букв:\n{ser[word_checks]}")

Слова, содержащие не менее 2 гласных букв:
0     Apple
1    Orange
3    Python
4     Money
dtype: object


## Упражнение № 24

In [51]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [52]:
import re

email_checks = emails.map(lambda email: bool(re.match(pattern, email)))
correct_emails = emails[email_checks]
print(f"Корректные адреса электронной почты из ряда:\n{correct_emails}")

Корректные адреса электронной почты из ряда:
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


## Упражнение № 25

In [53]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['apple', 'banana', 'banana', 'banana', 'carrot', 'carrot', 'apple', 'carrot', 'apple', 'apple']


In [54]:
mean_weights = weights.groupby(fruit).mean()
print(f"Корректные адреса электронной почты из ряда:\n{mean_weights}")

Корректные адреса электронной почты из ряда:
apple     6.750000
banana    3.000000
carrot    6.333333
dtype: float64


## Упражнение № 26

In [55]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [56]:
dist = np.linalg.norm(p - q)
print(f"Евклидово расстояние:\n{dist}")

Евклидово расстояние:
18.16590212458495


## Упражнение № 27

In [57]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [58]:
from scipy.signal import find_peaks

peak_idx, _ = find_peaks(ser)
print(peak_idx)

[1 5 7]


## Упражнение № 28

In [59]:
my_str = 'dbc deb abed gade'

In [60]:
from collections import Counter

symbol_to_replace = ' '
most_frequent_symbol = Counter(my_str).most_common(1)[0][0]

updated_str = my_str.replace(symbol_to_replace, most_frequent_symbol)
print(f"Строка с заменой пробелов на {most_frequent_symbol}:\n{updated_str}")

Строка с заменой пробелов на d:
dbcddebdabeddgade


## Упражнение № 29

In [61]:
begin_date = '2000-01-01'
ser = pd.Series(np.random.randint(1,10,10), pd.date_range(begin_date, periods=10, freq='W-SAT'))
print(f"Временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа:\n{ser}")

Временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа:
2000-01-01    3
2000-01-08    3
2000-01-15    7
2000-01-22    2
2000-01-29    4
2000-02-05    5
2000-02-12    2
2000-02-19    9
2000-02-26    3
2000-03-04    7
Freq: W-SAT, dtype: int32


## Упражнение № 30

In [62]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [63]:
all_dates = ser.resample('D').ffill()
print(f"Ряд с пропущенными датами:\n{all_dates}")

Ряд с пропущенными датами:
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64


## Упражнение № 31

In [64]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [65]:
print(f"Исходные данные:\n{ser}\n")

autocorrelations = [ser.autocorr(i) for i in range(1, 11)]
print(f"Автокорелляции для 10 лагов:\n{autocorrelations}")
print(f'Наибольшая корреляция: {np.argmax(np.abs(autocorrelations))}')

Исходные данные:
0     -6.417879
1      6.422714
2    -12.341777
3     -2.842709
4     -9.352236
5      5.740336
6     14.269341
7     -4.339745
8      3.996114
9      6.041776
10    11.072347
11    26.370222
12     9.434901
13    10.682020
14    33.822896
15     7.303931
16    24.263010
17    17.630914
18    16.024178
19    30.677142
dtype: float64

Автокорелляции для 10 лагов:
[0.35343685281194615, 0.5112909843354709, 0.5901087195385151, 0.25539628025484273, 0.7769217631921401, 0.3220709981658461, 0.09031388653167766, 0.6379071551915064, 0.07686705373041992, 0.24250520234745632]
Наибольшая корреляция: 4


## Упражнение № 32

In [66]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df = pd.read_csv(url)

chunk_index = 50
chunks = df.loc[df.index % chunk_index == 0]
print(f"Каждая 50-я строка набора данных:\n{chunks}")

Каждая 50-я строка набора данных:
         crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
50    0.08873  21.0   5.64     0  0.439  5.963   45.7  6.8147    4  243   
100   0.14866   0.0   8.56     0  0.520  6.727   79.9  2.7778    5  384   
150   1.65660   0.0  19.58     0  0.871  6.122   97.3  1.6180    5  403   
200   0.01778  95.0   1.47     0  0.403  7.135   13.9  7.6534    3  402   
250   0.14030  22.0   5.86     0  0.431  6.487   13.0  7.3967    7  330   
300   0.04417  70.0   2.24     0  0.400  6.871   47.4  7.8278    5  358   
350   0.06211  40.0   1.25     0  0.429  6.490   44.4  8.7921    1  335   
400  25.04610   0.0  18.10     0  0.693  5.987  100.0  1.5888   24  666   
450   6.71772   0.0  18.10     0  0.713  6.749   92.6  2.3236   24  666   
500   0.22438   0.0   9.69     0  0.585  6.027   79.7  2.4982    6  391   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  

## Упражнение № 33

In [67]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df = pd.read_csv(url, converters={'medv': lambda medv: 'High' if float(medv) > 25 else 'Low'})
print(f"Столбец 'medv' изменён на `Low` и `High`:\n{df}")

Столбец 'medv' изменён на `Low` и `High`:
        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98   Low  
1       1

## Упражнение № 34

In [68]:
L = pd.Series(range(15))
L

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
dtype: int64

In [69]:
df = pd.DataFrame(columns=['A', 'B', 'C', 'D'])

series_length = len(L)
for i in range(0, series_length - 3, 2):
    df.loc[i] = [L[i], L[i + 1], L[i + 2], L[i + 3]]

df

A   B   C   D
0    0   1   2   3
2    2   3   4   5
4    4   5   6   7
6    6   7   8   9
8    8   9  10  11
10  10  11  12  13

## Упражнение № 35

In [70]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
cols_to_use = ["crim", "medv"]

df = pd.read_csv(url, usecols=cols_to_use)
print(f"Испорт только столбцов {cols_to_use} в датафрейм:\n{df}")

Испорт только столбцов ['crim', 'medv'] в датафрейм:
        crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]


## Упражнение № 36

In [71]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

rows_range = df.index
print(f"Количество строк в датафрейме:\n{len(rows_range)}\n")

columns = df.columns
print(f"Количество столбцов в датафрейме:\n{len(columns)}\n")

print(f"Типы данных в датафрейме:\n{df.dtypes}\n")

df_stats = df.describe()
print(f"Суммарная статистика каждого столбца набора данных:\n{df_stats}\n")

df_arr = df.values
print(f"Эквивалент датафрейма в виде numpy-массива:\n{df_arr}\n")

df_list = df.values.tolist()
print(f"Эквивалент датафрейма в виде списка:\n{df_list}")

Количество строк в датафрейме:
93

Количество столбцов в датафрейме:
27

Типы данных в датафрейме:
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object

Суммарная статистика каждого столбца набора данных:
       Min.Price      Pr

## Упражнение № 37

In [72]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#*Какой производитель, модель и тип имеет наибольшую цену в `Price`? Каков номер строки и столбца ячейки с наибольшим значением `Price`?*

In [73]:
column = "Price"
max_price = df[column].max()

result = df.loc[df.Price == max_price, ["Manufacturer", "Model", "Type", column]]
print(f"Производитель, модель и тип имеет наибольшую цену в {column} + номер строки:\n{result}\n")

column_index = df.columns.get_loc(column)
print(f"Номер столбца {column}: {column_index}")

Производитель, модель и тип имеет наибольшую цену в Price + номер строки:
     Manufacturer Model     Type  Price
58  Mercedes-Benz  300E  Midsize   61.9

Номер столбца Price: 4


## Упражнение № 38

In [74]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [75]:
column_name = "Type"
new_column_name = "CarType"
df.rename(columns={column_name: new_column_name}, inplace=True)

symbol_to_replace = '.'
replacer_symbol = '_'
df.columns = df.columns.map(lambda x: x.replace(symbol_to_replace, replacer_symbol))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Упражнение № 39

In [76]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [77]:
cointains_null_msg = "Есть пропущенные значения"
no_null_msg = "Нет пропущенных значений"

contains_null_values = df.isnull().values.any()
print(cointains_null_msg if contains_null_values else no_null_msg)

Есть пропущенные значения


## Упражнение № 40

In [78]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [79]:
null_columns = df.apply(lambda x: x.isnull().sum())
print(f"Количество пропущенных значений в каждом столбце:\n{null_columns}\n")

max_null_col_index = null_columns.idxmax()
print(f"Столбец, имеющий наибольшее число пропущенных значений: {max_null_col_index}")

Количество пропущенных значений в каждом столбце:
Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Столбец, имеющий наибольшее число пропущенных значений: AirBags


## Упражнение № 41

In [80]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [81]:
min_price_col_name = "Min.Price"
min_price_col_mean_value = df[min_price_col_name].mean()
print(f"Ср. значение в {min_price_col_name}: {min_price_col_mean_value}")

max_price_col_name = "Max.Price"
max_price_col_mean_value = df[max_price_col_name].mean()
print(f"Ср. значение в {max_price_col_name}: {max_price_col_mean_value}\n")

df[min_price_col_name] = df[min_price_col_name].fillna(min_price_col_mean_value)
df[max_price_col_name] = df[max_price_col_name].fillna(max_price_col_mean_value)
df

Ср. значение в Min.Price: 17.118604651162787
Ср. значение в Max.Price: 21.45909090909091



Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

## Упражнение № 42

In [82]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [83]:
min_price_col_name = "Min.Price"
max_price_col_name = "Max.Price"

d = {min_price_col_name: np.nanmean, max_price_col_name: np.nanmedian}
df[[min_price_col_name, max_price_col_name]] = df[[min_price_col_name, max_price_col_name]].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1           NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2          Audi       90  Compact  25.900000   29.1      32.30      20.0   
3          Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4           BMW     535i  Midsize  17.118605   30.0      19.15      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7      22.70      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0      22.40      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3      23.70      18.0   
91        Volvo      240  Compact  21.800000   22.7      23.50      21.0   
92          NaN      850  Midsize  24.800000   26.7      28.50      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

## Упражнение № 43

In [84]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [85]:
df[['a']]

a
0   0
1   5
2  10
3  15

## Упражнение № 44

In [86]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [87]:
def swap_cols(column_to_swap: str, swapper_column: str):
    cols = list(df.columns.values)
    index_to_swap = cols.index(column_to_swap)
    swapper_index = cols.index(swapper_column)
    temp = cols[swapper_index]
    cols[swapper_index] = cols[index_to_swap]
    cols[index_to_swap] = temp
    return df[cols]

print(swap_cols('a', 'c'))
print(df[list(df.columns.values)[::-1]])

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


## Упражнение № 45

In [88]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [89]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

## Упражнение № 46

In [90]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

In [91]:
pd.options.display.float_format = '{:,.4f}'.format
df

random
0  0.0172
1  0.0000
2  0.0068
3  0.0181

In [92]:
pd.options.display.float_format = None

## Упражнение № 47

In [93]:
df = pd.DataFrame(np.random.random(4), columns=['random'])
df

random
0  0.859614
1  0.627095
2  0.591876
3  0.066281

In [94]:
pd.options.display.float_format = '{0:.2%}'.format
df

random
0  85.96%
1  62.71%
2  59.19%
3   6.63%

In [95]:
pd.options.display.float_format = None

## Упражнение № 48

In [96]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [97]:
print(df.loc[::20][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


## Упражнение № 49

In [98]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

In [99]:
new_value = 'missing'
cols_to_update_values_in = ['Manufacturer', 'Model', 'Type']
df[cols_to_update_values_in] = df[cols_to_update_values_in].fillna(new_value)
print(df)

   Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1       missing   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92      missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]


In [100]:
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df)

                          Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                   BMW     535i  Midsize        NaN        NaN
...                                ...      ...      ...        ...        ...
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6       22.7
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]


## Упражнение № 50

In [101]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df

a   b   c
0  29  28  18
1  19   9  16
2  16  16  15
3  11  25  10
4  25   2  27
5   1   7   6
6  29   2   7
7  28  29  21
8  24  13  17
9  27   2  24

In [102]:
df = df.sort_values(by=['a'], ascending=False)
df.iloc[4]

a    25
b     2
c    27
Name: 4, dtype: int32

## Упражнение № 51

In [103]:
ser = pd.Series(np.random.randint(1, 100, 15))
ser

0     25
1     31
2      2
3     10
4     73
      ..
10    87
11    96
12    96
13    18
14    22
Length: 15, dtype: int32

In [104]:
print(f"Исходные данные:\n{ser}\n")

mean = ser.mean()
print(f"Среднее значение: {mean}\n")

np.argwhere(ser > mean)[1]

Исходные данные:
0     25
1     31
2      2
3     10
4     73
      ..
10    87
11    96
12    96
13    18
14    22
Length: 15, dtype: int32

Среднее значение: 43.0



array([7], dtype=int64)

## Упражнение № 52

In [105]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   21  18  15  39
1   25  22  37  15
2   14  19  21  19
3   38  13  23  32
4   15  36  19  33
..  ..  ..  ..  ..
10  33  14  22  38
11  31  34  13  17
12  20  16  38  38
13  36  34  19  24
14  16  16  29  30

[15 rows x 4 columns]

In [106]:
df1 = df.sum(axis=1, numeric_only=True)
df1

0      93
1      99
2      73
3     106
4     103
     ... 
10    107
11     95
12    112
13    113
14     91
Length: 15, dtype: int64

In [107]:
df2 = df1[df1 > 100]
df2

3     106
4     103
5     129
9     102
10    107
12    112
13    113
dtype: int64

In [108]:
df3 = df2[-2::]
df3

12    112
13    113
dtype: int64

## Упражнение № 53

In [109]:
ser = pd.Series(np.logspace(-2, 2, 30))
ser

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
         ...    
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
Length: 30, dtype: float64

In [110]:
five_percentile = ser.quantile(0.05)
print(five_percentile)

nintyfive_percentile = ser.quantile(0.95)
print(nintyfive_percentile)

ser[ser < five_percentile] = five_percentile
ser[ser > nintyfive_percentile] = nintyfive_percentile
ser

0.016049294076965887
63.87667222018393


0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
        ...    
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
Length: 30, dtype: float64

## Упражнение № 54

In [111]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
df

0   1   2   3   4   5   6   7   8   9
0  33  -5  44 -11  33  35  -4  -7   7  22
1  24 -16  14 -20 -19  -9  24  23  -9  48
2   7  -9  26  28  18  43  -5   4  26  33
3  22  -4  15  34  15 -13 -12  21  43   6
4  16 -10  40  -2   4  18 -11 -13  48  15
5 -13  48 -15   9  35   8  27   9  37  28
6   1   1  41  -5  33 -17  27 -13  15  -4
7  31  37  48  15   7 -14  36   0  34 -18
8 -13  27  -5   8 -10 -20  36  26  26  40
9 -11  34 -13  26  -2  34  -7  -3  -5  17

In [112]:
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

n = int(arr_qualified.shape[0]**.5)

top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[33. 44. 33. 35. 22. 24. 24.]
 [23. 48. 26. 28. 18. 43. 26.]
 [33. 22. 15. 34. 15. 21. 43.]
 [16. 40. 18. 48. 48. 35. 27.]
 [37. 28. 41. 33. 27. 15. 31.]
 [37. 48. 15. 36. 34. 27. 36.]
 [26. 26. 40. 34. 26. 34. 17.]]


## Упражнение № 55

In [113]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [114]:
f_copy = df.iloc[1].copy()
s_copy = df.iloc[2].copy()
temp = f_copy
df.iloc[1] = s_copy
df.iloc[2] = temp
df

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

## Упражнение № 56

In [115]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))


In [116]:
df = df.iloc[::-1]


## Упражнение № 57

In [117]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [118]:
# How to create one-hot encodings of a categorical variable (dummy variables)?
df_onehot = pd.concat([pd.get_dummies(df['a'], dtype='int'), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


## Упражнение № 58

In [119]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df

0   1   2   3
0  88  70  10  92
1   9   4  64  29
2  70  37  21   7
3  15  59  77  74
4  20  59  66   3
5   6   5  19  33
6   9  22   6  88
7  44  30   9   1
8  56  91  77   5
9  30  31  52  75

In [120]:
columns_max_values = df.sum()
print(columns_max_values)

max_column = columns_max_values.idxmax()
print(max_column)

0    347
1    408
2    401
3    407
dtype: int64
1


## Упражнение № 59

In [121]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df

p   q   r   s
a  73  64  56  79
b  90  56  31  15
c  53  24  38  34
d  96  16  48  99
e  57  12  79  28
f  71   1  29  26
g  91  77  10  78
h  65  15  14  65
i  65  35  99   1
j  85  32  53  16

In [122]:
nearest_rows = []
nearest_distance = []

# итерируем по строкам
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i) 
    
    # инициализируем словарь, чтобы хранить евклидово расстояние для текущей строки
    e_dists = {}  
    
    # итерируем по остальным строкам для текущей строки    
    for j, contestant in rest.iterrows():        
        # вычисляем евклидово расстояние и обновляем e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})        
    
    # обновляем ближайшую строку для текущей строки и значение евклидово расстояния
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s nearest_row  dist
a  73  64  56  79           i    94
b  90  56  31  15           d    95
c  53  24  38  34           g    84
d  96  16  48  99           i   116
e  57  12  79  28           g   112
f  71   1  29  26           g    96
g  91  77  10  78           i   128
h  65  15  14  65           i   108
i  65  35  99   1           g   128
j  85  32  53  16           g    88

## Упражнение № 60

In [123]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

p   q   r   s   t   u   v   w   x   y
a  46  38  90  42  34  82  10   2  69  89
b  62  15  18   8  37  14  50  86  83  68
c  44  54  72  50  11   8  81  37   1  55
d  85  72  51  55  14  86  22  41  89   6
e  29  59  92  62  33  48  97  12  56  77
f  26  17  53  95  82  58  93  86  33  57
g  41  42  10  59  27   1  30  43  55  78
h  68  37  74  82  18  14  12  72  92  66

In [124]:
abs_corr = np.abs(df.corr())
max_corr = abs_corr.apply(lambda x: sorted(x)[-2])
print(np.round(max_corr.tolist(), 2))

[0.69 0.68 0.57 0.35 0.68 0.44 0.69 0.65 0.69 0.62]


## Упражнение № 61

In [125]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  73  92  22  61  16  90  38  62  69  20
1  56  13   1  80  23  49   9  99  41  58
2  95  71  60  16  23  95  69  19   6  13
3  16  96  16  40  44  93   5  63  78  54
4   6  89  79  53  77  44  78  17  89  25
5  58  20  67  93  25  68  35  97  72   2
6  46  70  48  79  52  30  25  73  57  27
7  60  42  51  66  34  45  98  17  37  24

In [126]:
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)
min_by_max

0    0.173913
1    0.010101
2    0.063158
3    0.052083
4    0.067416
5    0.020619
6    0.316456
7    0.173469
dtype: float64

## Упражнение № 62

In [127]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  44  95  23  44  95   6  94  64  64  97
1  98  50   5  13  14  51  23  91  98   7
2  59  48   1  45  33   9  86  13  42  29
3  31  17  76  30  26  38  40  21  57  58
4  73  54   8   7  49  27  88  75  29  43
5  30  67  94  49  48  75  12  40  71  21
6  65  20  83  56  38  36  96  36  97  68
7  76  54  30  29  53  53  93  13  34  26

In [128]:
new_col_name = "penultimate"

updated_df = df.apply(lambda x: x.sort_values().to_list()[-2], axis=1)
df[new_col_name] = updated_df
df

0   1   2   3   4  ...   6   7   8   9  penultimate
0  44  95  23  44  95  ...  94  64  64  97           95
1  98  50   5  13  14  ...  23  91  98   7           98
2  59  48   1  45  33  ...  86  13  42  29           59
3  31  17  76  30  26  ...  40  21  57  58           58
4  73  54   8   7  49  ...  88  75  29  43           75
5  30  67  94  49  48  ...  12  40  71  21           75
6  65  20  83  56  38  ...  96  36  97  68           96
7  76  54  30  29  53  ...  93  13  34  26           76

[8 rows x 11 columns]

## Упражнение № 63

In [129]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  94  33  94   1  44  77  79  74   2   6
1  14   2  36  69  55  85  85  59  57  69
2  71  35  78  50  41  43  63  99  48   5
3  21  61   9   1  84  79  27  48  60  93
4  30  91  85  50  71  47  46  20   6  61
5  70  54  30  60  55  39  37  13  40   2
6  60  66  67  56  54  69  37  67  93  15
7  41   7   2  15  49  92  99   5  75  79

In [130]:
df1 = df.apply(lambda row: (row - row.mean()) / row.std(), axis=1)
df1

0         1         2         3         4         5         6  \
0  1.147969 -0.458135  1.147969 -1.300681 -0.168509  0.700367  0.753026   
1 -1.399317 -1.828775 -0.611978  0.569032  0.067998  1.141642  1.141642   
2  0.681548 -0.704652  0.951087 -0.127068 -0.473618 -0.396607  0.373504   
3 -0.840537  0.391019 -1.210004 -1.456316  1.099164  0.945220 -0.655804   
4 -0.757311  1.474379  1.254869 -0.025610  0.742677 -0.135365 -0.171950   
5  1.422314  0.663747 -0.474105  0.948209  0.711157 -0.047410 -0.142231   
6  0.077016  0.365825  0.413959 -0.115524 -0.211793  0.510229 -1.030085   
7 -0.142158 -1.037225 -1.168853 -0.826621  0.068446  1.200443  1.384722   

          7         8         9  
0  0.621378 -1.274351 -1.169033  
1  0.211150  0.139574  0.569032  
2  1.759704 -0.204079 -1.859818  
3 -0.009237  0.360230  1.376264  
4 -1.123162 -1.635354  0.376826  
5 -1.280083  0.000000 -1.801598  
6  0.413959  1.665465 -2.089051  
7 -1.089876  0.752910  0.858212

In [131]:
df2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
df2

0     1     2     3     4     5     6     7     8     9
0  0.00  0.65  0.00  1.00  0.93  0.28  0.28  0.27  1.00  0.96
1  1.00  1.00  0.63  0.00  0.67  0.13  0.19  0.43  0.40  0.26
2  0.29  0.63  0.17  0.28  1.00  0.92  0.50  0.00  0.49  0.97
3  0.91  0.34  0.92  1.00  0.00  0.25  1.00  0.54  0.36  0.00
4  0.80  0.00  0.10  0.28  0.30  0.85  0.74  0.84  0.96  0.35
5  0.30  0.42  0.70  0.13  0.67  1.00  0.86  0.91  0.58  1.00
6  0.42  0.28  0.29  0.19  0.70  0.43  0.86  0.34  0.00  0.86
7  0.66  0.94  1.00  0.79  0.81  0.00  0.00  1.00  0.20  0.15

## Упражнение № 64

In [132]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  61  34  46   8  52  49  39   3  92  73
1  60  81  10  96  63  42  41  14  40  27
2  48  29  76  61  99  67   1  27  56  16
3  70  43  85   9  53  44  79  18  11  21
4  91   6  92  15   5   2  23   7  55  21
5  32  63  12  55  96  95  71  68  96  33
6  45  44  13  84  64  35  76  61  66  77
7  26  24  10  92  71   6   9  47   6  63

In [133]:
length = len(df.index) - 1
correlations = []
for i in range(length):
    current_row = df.iloc[i]
    next_row = df.iloc[i + 1]
    corr = current_row.corr(next_row).round(3)
    correlations.append(corr)

correlations

[-0.206, 0.166, 0.072, 0.472, -0.616, 0.307, 0.591]

## Упражнение № 65

In [134]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df

0   1   2   3   4   5   6   7   8   9
0  92  14  69  65  73  50  44  83  13  57
1  17  70  84  40  84  47  23  64  84  20
2  74  29  80  21   1  34  18  76  70  51
3  75  27  19  64  25  19  55  97  35  94
4  71  17   3  39  75  56  29  12  30  63
5  40  38   3  62  68  10  21  25  30  41
6  25  98  68  43  75  86  14  83  51  51
7  63  60  15  87  49  85  99  87  61  22
8   9  13  33  17   9  24  73  15  32  20
9  80  94   6  90  55  27  85  65  25  10

In [135]:
length = df.shape[0]
for i in range(length):
    df.iat[i, i] = 0
    df.iat[length - i - 1, i] = 0

df

0   1   2   3   4   5   6   7   8   9
0   0  14  69  65  73  50  44  83  13   0
1  17   0  84  40  84  47  23  64   0  20
2  74  29   0  21   1  34  18   0  70  51
3  75  27  19   0  25  19   0  97  35  94
4  71  17   3  39   0   0  29  12  30  63
5  40  38   3  62   0   0  21  25  30  41
6  25  98  68   0  75  86   0  83  51  51
7  63  60   0  87  49  85  99   0  61  22
8   9   0  33  17   9  24  73  15   0  20
9   0  94   6  90  55  27  85  65  25   0

## Упражнение № 66

In [136]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
df

col1      col2  col3
0   apple  0.701102     0
1  banana  0.481631     6
2  orange  0.399068     9
3   apple  0.976014     7
4  banana  0.765375     9
5  orange  0.919252    14
6   apple  0.088886    10
7  banana  0.355570    13
8  orange  0.416406     2

In [137]:
needed_group = 'apple'
df_grouped.get_group(needed_group)

col1      col2  col3
0  apple  0.701102     0
3  apple  0.976014     7
6  apple  0.088886    10

## Упражнение № 67

In [138]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df

fruit    rating  price
0   apple  0.464285      5
1  banana  0.593581      6
2  orange  0.400467     14
3   apple  0.013885      6
4  banana  0.266167      6
5  orange  0.239179      1
6   apple  0.231055      4
7  banana  0.785321      0
8  orange  0.103316      7

In [139]:
needed_fruit = "banana"
grouped_df = df.groupby(["fruit"])
filtered_df = df_grouped.get_group(needed_fruit)
filtered_df

col1      col2  col3
1  banana  0.481631     6
4  banana  0.765375     9
7  banana  0.355570    13

In [140]:
filtered_df.sort_values(by='col2').iloc[-2]

col1      banana
col2    0.481631
col3           6
Name: 1, dtype: object

## Упражнение № 68

In [141]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df

fruit    rating  price
0   apple  0.414162     11
1  banana  0.823281      4
2  orange  0.765292      5
3   apple  0.615565     11
4  banana  0.981857     14
5  orange  0.053579     13
6   apple  0.795132      6
7  banana  0.628108     12
8  orange  0.231064      9

In [142]:
grouped_items = df.groupby('fruit', as_index=False)['price'].mean()
print(grouped_items)

    fruit      price
0   apple   9.333333
1  banana  10.000000
2  orange   9.000000


## Упражнение № 69

In [143]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})
print(f"Датафрейм x:\n{df1}\n")

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
print(f"Датафрейм y:\n{df2}")

Датафрейм x:
    fruit  weight  price
0   apple    high      4
1  banana  medium      3
2  orange     low     14
3   apple    high      1
4  banana  medium      6
5  orange     low     10
6   apple    high      1
7  banana  medium      4
8  orange     low      9

Датафрейм y:
   pazham  kilo  price
0   apple  high     10
1  orange   low     11
2    pine  high     10
3   apple   low     12
4  orange  high     13
5    pine   low      2


In [144]:
new_df = pd.merge(df1, df2,  how='inner', left_on=['fruit','weight'], right_on = ['pazham','kilo'])
new_df

fruit weight  price_x  pazham  kilo  price_y
0   apple   high        4   apple  high       10
1   apple   high        1   apple  high       10
2   apple   high        1   apple  high       10
3  orange    low       14  orange   low       11
4  orange    low       10  orange   low       11
5  orange    low        9  orange   low       11

## Упражнение № 70

In [145]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df

a   b   c   d
0  85  47  67  60
1  45  77  77  86
2  34  64  66  62
3   9  14  78  54
4  96  75  48  23

In [146]:
col_name_a = 'a'
col_name_b = 'b'
new_col_name_a = "lag1"
new_col_name_b = "lead1"

df[new_col_name_a] = df[col_name_a].shift(1)
df[new_col_name_b] = df[col_name_b].shift(-1)
df

a   b   c   d  lag1  lead1
0  85  47  67  60   NaN   77.0
1  45  77  77  86  85.0   64.0
2  34  64  66  62  45.0   14.0
3   9  14  78  54  34.0   75.0
4  96  75  48  23   9.0    NaN

## Упражнение № 71

In [147]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df

a  b  c  d
0  1  7  9  8
1  4  4  7  6
2  7  4  2  5
3  2  6  5  1
4  8  7  6  6

In [148]:
values, counts = np.unique(df.values,return_counts=True)
np.stack([values, counts])

array([[1, 2, 4, 5, 6, 7, 8, 9],
       [2, 2, 3, 2, 4, 4, 2, 1]], dtype=int64)

## Упражнение № 72

In [149]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka


In [150]:
df = df.row.str.split(',|\t', expand=True)

new_header = df.iloc[0]
new_df = df[1:]
new_df.columns = new_header
print(new_df)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
